import {
  to = segment_destination_subscription.id-63ced4b99610921d2b5ce474_82GybidGtkeSEEcoPHpAjq
  id = "63ced4b99610921d2b5ce474:82GybidGtkeSEEcoPHpAjq"
}

resource "segment_destination_subscription" "id-63ced4b99610921d2b5ce474_82GybidGtkeSEEcoPHpAjq" {
  action_id      = "2n3RKy5oyzS1kLdEEYV99N"
  destination_id = "63ced4b99610921d2b5ce474"
  enabled        = true
  model_id       = null
  name           = "VBT - Adjust OMS Indicated"
  settings       = "{\"adjustment_timestamp\":{\"@path\":\"$.timestamp\"},\"adjustment_type\":\"RETRACTION\",\"city\":{\"@if\":{\"else\":{\"@path\":\"$.context.traits.address.city\"},\"exists\":{\"@template\":\"{{properties.address.city,}}\"},\"then\":{\"@template\":\"{{properties.address.city,}}\"}}},\"conversion_action\":\"6475761018\",\"conversion_timestamp\":{\"@path\":\"$.originalTimestamp\"},\"country\":{\"@if\":{\"else\":{\"@path\":\"$.context.traits.address.country\"},\"exists\":{\"@template\":\"{{properties.address.country,}}\"},\"then\":{\"@template\":\"{{properties.address.country,}}\"}}},\"email_address\":{\"@if\":{\"else\":{\"@path\":\"$.context.traits.email\"},\"exists\":{\"@path\":\"$.properties.email\"},\"then\":{\"@path\":\"$.properties.email\"}}},\"first_name\":{\"@if\":{\"else\":{\"@path\":\"$.context.traits.firstName\"},\"exists\":{\"@path\":\"$.properties.firstName\"},\"then\":{\"@path\":\"$.properties.firstName\"}}},\"gclid\":{\"@path\":\"$.properties.gclid\"},\"last_name\":{\"@if\":{\"else\":{\"@path\":\"$.context.traits.lastName\"},\"exists\":{\"@path\":\"$.properties.lastName\"},\"then\":{\"@path\":\"$.properties.lastName\"}}},\"phone_number\":{\"@if\":{\"else\":{\"@path\":\"$.context.traits.phone\"},\"exists\":{\"@path\":\"$.properties.phone\"},\"then\":{\"@path\":\"$.properties.phone\"}}},\"postal_code\":{\"@if\":{\"else\":{\"@path\":\"$.context.traits.address.postalCode\"},\"exists\":{\"@template\":\"{{properties.address.postalCode,}}\"},\"then\":{\"@template\":\"{{properties.address.postalCode,}}\"}}},\"restatement_currency_code\":\"USD\",\"restatement_value\":\"0\",\"state\":{\"@if\":{\"else\":{\"@path\":\"$.context.traits.address.state\"},\"exists\":{\"@template\":\"{{properties.address.state,}}\"},\"then\":{\"@template\":\"{{properties.address.state,}}\"}}},\"street_address\":{\"@if\":{\"else\":{\"@path\":\"$.context.traits.address.street\"},\"exists\":{\"@template\":\"{{properties.address.street,}}\"},\"then\":{\"@template\":\"{{properties.address.street,}}\"}}},\"user_agent\":{\"@path\":\"$.context.userAgent\"}}"
  trigger        = "event = \"OMS indicated\" and properties.gclid != null and properties.oms_indicated_provider = \"None\""
}